name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create ZIP package
      run: zip -r deploy_package.zip . -x '*.git*'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload ZIP to S3
      run: |
        aws s3 cp deploy_package.zip s3://$S3_BUCKET/deploy_package.zip
      env:
        S3_BUCKET: ${{ secrets.EB_S3_BUCKET }}

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APP_NAME }}
        environment_name: ${{ secrets.EB_ENV_NAME }}
        version_label: eb-${{ github.sha }}
        region: ${{ secrets.AWS_REGION }}
        existing_bucket_name: ${{ secrets.EB_S3_BUCKET }}
        deployment_package: deploy_package.zip
